# Parameter configuration

# General specifications
result_path: '../results'                # Relative base path for DEAN-TS results and model information
dataset_path: '../datasets/'             # Relative base path for datasets
seed: 21                                 # Randomness seed for reproducible results
ensemble_size: 50                        # Number of models to train

# Submodel specifications
lr: 0.03            # Learning rate
batch: 16           # Batch size
depth: 3            # Number of layers for each base detector network
bag: 64              # Dimensionality for each base model (bag - 1 lag features will be chosen)
look_back: 256       # How many previous time steps are taken into consideration for feature selection
